import { FamilyName, GivenName, Sex, Human } from "./humanType";

const HumanFamilyNames: Array<FamilyName> = [
  { familyName: "佐藤", familyNameKana: "サトウ" },
  { familyName: "鈴木", familyNameKana: "スズキ" },
  { familyName: "高橋", familyNameKana: "タカハシ" },
  { familyName: "田中", familyNameKana: "タナカ" },
  { familyName: "伊藤", familyNameKana: "イトウ" },
  { familyName: "山本", familyNameKana: "ヤマモト" },
  { familyName: "渡辺", familyNameKana: "ワタナベ" },
  { familyName: "中村", familyNameKana: "ナカムラ" },
  { familyName: "小林", familyNameKana: "コバヤシ" },
  { familyName: "加藤", familyNameKana: "カトウ" },
  { familyName: "吉田", familyNameKana: "ヨシダ" },
  { familyName: "山田", familyNameKana: "ヤマダ" },
  { familyName: "佐々木", familyNameKana: "ササキ" },
  { familyName: "山口", familyNameKana: "ヤマグチ" },
  { familyName: "松本", familyNameKana: "マツモト" },
  { familyName: "井上", familyNameKana: "イノウエ" },
  { familyName: "木村", familyNameKana: "キムラ" },
  { familyName: "林", familyNameKana: "ハヤシ" },
  { familyName: "斎藤", familyNameKana: "サイトウ" },
  { familyName: "清水", familyNameKana: "シミズ" },
  { familyName: "山崎", familyNameKana: "ヤマザキ" },
  { familyName: "阿部", familyNameKana: "アベ" },
  { familyName: "森", familyNameKana: "モリ" },
  { familyName: "池田", familyNameKana: "イケダ" },
  { familyName: "橋本", familyNameKana: "ハシモト" },
  { familyName: "山下", familyNameKana: "ヤマモト" },
  { familyName: "石川", familyNameKana: "イシカワ" },
  { familyName: "中島", familyNameKana: "ナカジマ" },
  { familyName: "前田", familyNameKana: "マエダ" },
  { familyName: "藤田", familyNameKana: "フジタ" },
  { familyName: "後藤", familyNameKana: "ゴトウ" },
  { familyName: "小川", familyNameKana: "オガワ" },
  { familyName: "岡田", familyNameKana: "オカダ" },
  { familyName: "村上", familyNameKana: "ムラカミ" },
  { familyName: "長谷川", familyNameKana: "ハセガワ" },
  { familyName: "近藤", familyNameKana: "コンドウ" },
  { familyName: "石井", familyNameKana: "イシイ" },
  { familyName: "斉藤", familyNameKana: "サイトウ" },
  { familyName: "坂本", familyNameKana: "サカモト" },
  { familyName: "遠藤", familyNameKana: "エンドウ" },
  { familyName: "藤井", familyNameKana: "フジイ" },
  { familyName: "青木", familyNameKana: "アオキ" },
  { familyName: "福田", familyNameKana: "フクダ" },
  { familyName: "三浦", familyNameKana: "ミウラ" },
  { familyName: "西村", familyNameKana: "ニシムラ" },
  { familyName: "藤原", familyNameKana: "フジワラ" },
  { familyName: "太田", familyNameKana: "オオタ" },
  { familyName: "松田", familyNameKana: "マツダ" },
  { familyName: "原田", familyNameKana: "ハラダ" },
  { familyName: "岡本", familyNameKana: "オカモト" },
  { familyName: "中野", familyNameKana: "ナカノ" },
  { familyName: "中川", familyNameKana: "ナカガワ" },
  { familyName: "小野", familyNameKana: "オノ" },
  { familyName: "田村", familyNameKana: "タムラ" },
  { familyName: "竹内", familyNameKana: "タケウチ" },
  { familyName: "金子", familyNameKana: "カネコ" },
  { familyName: "中山", familyNameKana: "ナカヤマ" },
  { familyName: "和田", familyNameKana: "ワダ" },
  { familyName: "石田", familyNameKana: "イシダ" },
  { familyName: "工藤", familyNameKana: "クドウ" },
  { familyName: "上田", familyNameKana: "ウエダ" },
  { familyName: "原", familyNameKana: "ハラ" },
  { familyName: "森田", familyNameKana: "モリタ" },
  { familyName: "酒井", familyNameKana: "サカイ" },
  { familyName: "横山", familyNameKana: "ヨコヤマ" },
  { familyName: "柴田", familyNameKana: "シバタ" },
  { familyName: "宮崎", familyNameKana: "ミヤザキ" },
  { familyName: "宮本", familyNameKana: "ミヤモト" },
  { familyName: "内田", familyNameKana: "ウチダ" },
  { familyName: "高木", familyNameKana: "タカギ" },
  { familyName: "谷口", familyNameKana: "タニグチ" },
  { familyName: "安藤", familyNameKana: "アンドウ" },
  { familyName: "丸山", familyNameKana: "マルイ" },
  { familyName: "今井", familyNameKana: "イマノ" },
  { familyName: "大野", familyNameKana: "オオノ" },
  { familyName: "高田", familyNameKana: "タカダ" },
  { familyName: "菅原", familyNameKana: "スガワラ" },
  { familyName: "河野", familyNameKana: "カワノ" },
  { familyName: "武田", familyNameKana: "タケダ" },
  { familyName: "藤本", familyNameKana: "フジモト" },
  { familyName: "上野", familyNameKana: "ウエノ" },
  { familyName: "杉山", familyNameKana: "スギヤマ" },
  { familyName: "千葉", familyNameKana: "チバ" },
  { familyName: "村田", familyNameKana: "ムラタ" },
  { familyName: "増田", familyNameKana: "マスダ" },
  { familyName: "小島", familyNameKana: "コジマ" },
  { familyName: "小山", familyNameKana: "コヤマ" },
  { familyName: "大塚", familyNameKana: "オオツカ" },
  { familyName: "平野", familyNameKana: "ヒラノ" },
  { familyName: "久保", familyNameKana: "クボ" },
  { familyName: "渡部", familyNameKana: "ワタベ" },
  { familyName: "松井", familyNameKana: "マツイ" },
  { familyName: "菊地", familyNameKana: "キクチ" },
  { familyName: "岩崎", familyNameKana: "イワサキ" },
  { familyName: "松尾", familyNameKana: "マツオ" },
  { familyName: "佐野", familyNameKana: "サノ" },
  { familyName: "木下", familyNameKana: "キノシタ" },
  { familyName: "野口", familyNameKana: "ノグチ" },
  { familyName: "野村", familyNameKana: "ノムラ" },
  { familyName: "新井", familyNameKana: "アライ" }
];

const HumanGivenNamesMale: Array<GivenName> = [
  { givenName: "翔太", givenNameKana: "ショウタ" },
  { givenName: "蓮", givenNameKana: "レン" },
  { givenName: "陸", givenNameKana: "リク" },
  { givenName: "颯太", givenNameKana: "フウタ" },
  { givenName: "悠斗", givenNameKana: "ユウト" },
  { givenName: "大翔", givenNameKana: "ダイト" },
  { givenName: "翔", givenNameKana: "ショウ" },
  { givenName: "翼", givenNameKana: "ツバサ" },
  { givenName: "樹", givenNameKana: "イツキ" },
  { givenName: "奏太", givenNameKana: "ソウタ" },
  { givenName: "大和", givenNameKana: "ヤマト" },
  { givenName: "大輝", givenNameKana: "ダイキ" },
  { givenName: "悠", givenNameKana: "ユウ" },
  { givenName: "隼人", givenNameKana: "ハヤト" },
  { givenName: "健太", givenNameKana: "ケンタ" },
  { givenName: "大輔", givenNameKana: "ダイスケ" },
  { givenName: "駿", givenNameKana: "シュン" },
  { givenName: "陽斗", givenNameKana: "ハルト" },
  { givenName: "優", givenNameKana: "ユウ" },
  { givenName: "陽", givenNameKana: "ヨウ" },
  { givenName: "悠人", givenNameKana: "ユウト" },
  { givenName: "誠", givenNameKana: "マコト" },
  { givenName: "拓海", givenNameKana: "タクミ" },
  { givenName: "仁", givenNameKana: "ジン" },
  { givenName: "悠太", givenNameKana: "ユウタ" },
  { givenName: "悠真", givenNameKana: "ユウマ" },
  { givenName: "大地", givenNameKana: "ダイチ" },
  { givenName: "健", givenNameKana: "ケン" },
  { givenName: "遼", givenNameKana: "リョウ" },
  { givenName: "大樹", givenNameKana: "ダイキ" },
  { givenName: "諒", givenNameKana: "リョウ" },
  { givenName: "響", givenNameKana: "ヒビキ" },
  { givenName: "太一", givenNameKana: "タイチ" },
  { givenName: "太郎", givenNameKana: "タロウ" },
  { givenName: "優斗", givenNameKana: "ユウト" },
  { givenName: "亮", givenNameKana: "リョウ" },
  { givenName: "海斗", givenNameKana: "カイト" },
  { givenName: "颯", givenNameKana: "ハヤト" },
  { givenName: "亮太", givenNameKana: "リョウタ" },
  { givenName: "匠", givenNameKana: "タクミ" },
  { givenName: "陽太", givenNameKana: "ヨウタ" },
  { givenName: "航", givenNameKana: "ワタル" },
  { givenName: "瑛太", givenNameKana: "エイタ" },
  { givenName: "直樹", givenNameKana: "ナオキ" },
  { givenName: "空", givenNameKana: "ソラ" },
  { givenName: "光", givenNameKana: "ヒカル" },
  { givenName: "輝", givenNameKana: "アキラ" },
  { givenName: "一輝", givenNameKana: "カズキ" },
  { givenName: "健一", givenNameKana: "ケンイチ" },
  { givenName: "浩二", givenNameKana: "コウジ" },
  { givenName: "哲也", givenNameKana: "テツヤ" },
  { givenName: "剛", givenNameKana: "ツヨシ" },
  { givenName: "修", givenNameKana: "オサム" },
  { givenName: "徹", givenNameKana: "テツ" },
  { givenName: "秀樹", givenNameKana: "ヒデキ" },
  { givenName: "隆", givenNameKana: "タカシ" },
  { givenName: "蒼", givenNameKana: "アオイ" }
];

const HumanGivenNamesFemale: Array<GivenName> = [
  { givenName: "葵", givenNameKana: "アオイ" },
  { givenName: "優那", givenNameKana: "ユウナ" },
  { givenName: "優奈", givenNameKana: "ユウナ" },
  { givenName: "凛", givenNameKana: "リン" },
  { givenName: "陽菜", givenNameKana: "ヒナ" },
  { givenName: "愛", givenNameKana: "アイ" },
  { givenName: "結衣", givenNameKana: "ユイ" },
  { givenName: "美咲", givenNameKana: "ミサキ" },
  { givenName: "楓", givenNameKana: "カエデ" },
  { givenName: "さくら", givenNameKana: "サクラ" },
  { givenName: "遥", givenNameKana: "ハルカ" },
  { givenName: "美優", givenNameKana: "ミユ" },
  { givenName: "莉子", givenNameKana: "リコ" },
  { givenName: "七海", givenNameKana: "ナナミ" },
  { givenName: "美月", givenNameKana: "ミツキ" },
  { givenName: "結菜", givenNameKana: "ユウナ" },
  { givenName: "真央", givenNameKana: "マオ" },
  { givenName: "花音", givenNameKana: "カノン" },
  { givenName: "陽子", givenNameKana: "ハルコ" },
  { givenName: "舞", givenNameKana: "マイ" },
  { givenName: "美羽", givenNameKana: "ミウ" },
  { givenName: "優衣", givenNameKana: "ユイ" },
  { givenName: "未来", givenNameKana: "ミライ" },
  { givenName: "彩", givenNameKana: "アヤ" },
  { givenName: "彩乃", givenNameKana: "アヤノ" },
  { givenName: "彩花", givenNameKana: "アヤカ" },
  { givenName: "優", givenNameKana: "ユウ" },
  { givenName: "智子", givenNameKana: "トモコ" },
  { givenName: "奈々", givenNameKana: "ナナ" },
  { givenName: "千尋", givenNameKana: "チヒロ" },
  { givenName: "愛美", givenNameKana: "マナミ" },
  { givenName: "優菜", givenNameKana: "ユウナ" },
  { givenName: "杏", givenNameKana: "アンズ" },
  { givenName: "裕子", givenNameKana: "ユウコ" },
  { givenName: "芽衣", givenNameKana: "メイ" },
  { givenName: "綾乃", givenNameKana: "アヤノ" },
  { givenName: "琴音", givenNameKana: "コトネ" },
  { givenName: "桜", givenNameKana: "サクラ" },
  { givenName: "恵", givenNameKana: "メグミ" },
  { givenName: "杏奈", givenNameKana: "アンナ" },
  { givenName: "美桜", givenNameKana: "ミハル" },
  { givenName: "優花", givenNameKana: "ユウカ" },
  { givenName: "玲奈", givenNameKana: "レナ" },
  { givenName: "結", givenNameKana: "ユイ" },
  { givenName: "茜", givenNameKana: "アカネ" },
  { givenName: "美穂", givenNameKana: "ミホ" },
  { givenName: "明日香", givenNameKana: "アスカ" },
  { givenName: "愛子", givenNameKana: "アイコ" },
  { givenName: "美緒", givenNameKana: "ミオ" },
  { givenName: "碧", givenNameKana: "ミドリ" },
  { givenName: "麻衣", givenNameKana: "マイ" },
  { givenName: "友美", givenNameKana: "トモミ" },
  { givenName: "美香", givenNameKana: "ミカ" },
  { givenName: "智美", givenNameKana: "トモミ" },
  { givenName: "麻衣子", givenNameKana: "マイコ" },
  { givenName: "香織", givenNameKana: "カオリ" },
  { givenName: "麻美", givenNameKana: "アサミ" }
];

const createRandomIndex = (arr: Array<any>) => {
  return Math.floor(Math.random() * arr.length);
};

const createRandomSex = (): Sex => {
  const seed = Math.floor(Math.random() * 2);
  if (seed === 0) return "male";
  return "female";
};

export const createHumanInstance = (): Human => {
  const familyName: FamilyName =
    HumanFamilyNames[createRandomIndex(HumanFamilyNames)];
  const sex = createRandomSex();
  let givenName: GivenName;
  if (sex === "male") {
    givenName = HumanGivenNamesMale[createRandomIndex(HumanGivenNamesMale)];
  } else {
    givenName = HumanGivenNamesFemale[createRandomIndex(HumanGivenNamesFemale)];
  }
  return {
    ...familyName,
    ...givenName,
    sex: sex
  };
};

export const createRandomHumanInstances = (num: number): Array<Human> => {
  const result = [];
  for (let i = 1; i <= num; i++) {
    result.push(createHumanInstance());
  }
  return result;
};
